version: "3"

services:
  app:
    build: .
    env_file:
      - .env
    environment:
      DB_HOST: mysql
    ports:
      - "3000:${PORT}"
    depends_on:
      - mysql
  mysql:
    image: mysql:9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:3306"
