apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nest-app
  template:
    metadata:
      labels:
        app: nest-app
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command: [ "sh", "-c", "until nc -z mysql 3306; do echo waiting for mysql; sleep 3; done;" ]
      containers:
        - name: nest-app
          image: gcr.io/devops-project-451319/nest-app:latest
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: mysql
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root-password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: database
          ports:
            - containerPort: 3000
